COURSE_ACTS(COURSE_BOB, _(" 1 STAR PALACE"),	_("CHAIN CHOMP'S STAR"),	_("BLAST TO THE STARRY SKY"),	_("8 RED STARBITS AROUND THE STARS"),	_("THE SECRET OF THE STAR PILLARS"),	_("THE SECRET STAR PUZZLE"),	_("KING STARSTONE ON THE STAR TOP"))

COURSE_ACTS(COURSE_WF, _(" 2 FOREST VALLEY"),	_("CLIMBING THE TOWER"),	_("KING WHOMP'S FOREST FORTRESS"),	_("ACROSS THE FOREST"),	_("8 RED STARBITS DEEP IN THE FOREST"),	_("THE LONELY TREE"),	_("THE SECRET WALL-KICK"))

COURSE_ACTS(COURSE_JRB, _(" 3 DEEP WATER COVE"),	_("DEEP DIVE IN THE COVE"),	_("EXPLORING THE CAVERN"),	_("DIVING DEEP IN THE SECRET CAVE"),	_("THE BIG CAVERN CLIMB"),	_("A DEEP DIVE FOR 8 RED STARBITS"),	_("A DEEP WATERY MYSTERY"))

COURSE_ACTS(COURSE_CCM, _(" 4 SKY LAND GARDEN"),	_("THE GARDEN'S FLOWERY SUMMIT"),	_("TO THE TOP OF THE SKY FORT"),	_("8 RED STARBITS IN THE GARDEN"),	_("THE GRAND TOWER"),	_("WING MARIO OVER THE GARDEN"),	_("WIGGLER SHOWDOWN"))

COURSE_ACTS(COURSE_BBH, _(" 5 DARK MOUNTAIN VALLEY"),	_("CLIMBING UP THE WALL"),	_("TOP OF THE DARK MOUNTAIN"),	_("THE SECRET CAVE"),	_("ACROSS THE VALLEY'S DEEP WOODS"),	_("THE VALLEY'S RED STARBITS"),	_("THE SECRET OF THE VALLEY"))

COURSE_ACTS(COURSE_HMC, _(" 6 THE SECRET CAVERN"),	_("CLIMBING OVER THE LAVA"),	_("THE RED-HOT TOWER"),	_("IN THE DEPTHS OF THE CAVERN"),	_("THROUGH THE DANGEROUS PATH"),	_("CAVERN'S 8 RED STARBITS"),	_("THE HIDDEN ROOM"))

COURSE_ACTS(COURSE_LLL, _(" 7 AUTUMN FIELDS"),	_("ACROSS THE FIELDS OF AUTUMN"),	_("TOP OF THE AUTUMN TOWER"),	_("INSIDE AUTUMN FIELD'S CAVERN"),	_("RED STARBITS IN AUTUMN"),	_("THE SECRET OF AUTUMN FIELD"),	_("THE HIDDEN MYSTIC STAR"))

COURSE_ACTS(COURSE_SSL, _(" 8 FREEZY FLAME VALLEY"),	_("TOP OF THE SUMMIT"),	_("FREEZY FLAME'S BLISTERING CORE"),	_("THE ICE CAVERN"),	_("ICY FLAMING RED STARBITS"),	_("FLYING THROUGH THE FROZEN SKY"),	_("MYSTERY OF FREEZY FLAME VALLEY"))

COURSE_ACTS(COURSE_DDD, _(" 9 SKY CASTLE PALACE"),	_("TOP OF THE ROYAL TOWER"),	_("CLIMBING THE HUGE PALACE TOWER"),	_("THE CASTLE IN THE SKY"),	_("SECRET OF THE FLOWER GARDEN"),	_("SKY'S 8 RED STARBITS"),	_("THE LONELY SKY PLATFORM"))

COURSE_ACTS(COURSE_SL, _("10 STARDUST CAVERN"),	_("THE STARDUST CLIMB"),	_("DEEP IN THE CAVERN"),	_("SECRET OF STARDUST RUINS"),	_("FLYING IN THE CAVERN"),	_("RED STARBITS OF STARDUST CAVERN"),	_("FIND THE MYSTIC STAR"))

COURSE_ACTS(COURSE_WDW, _("11 HOT LAVA FLOATS"),	_("THE FLOATING VOLCANO"),	_("JUMPING THROUGH LAVA FLOATS"),	_("METAL-LAVA WALL-KICKS"),	_("FLYING OVER THE LAVA FLOATS"),	_("THE HOT FLOATING RED STARBITS"),	_("PERIL IN THE LAVA RING"))

COURSE_ACTS(COURSE_TTM, _("12 WATER TEMPLE"),	_("THE TEMPLE'S TALL PILLAR"),	_("THE HUGE TOWER"),	_("THE TEMPLE'S CASTLE"),	_("MYSTIC STAR OF THE TEMPLE"),	_("WATER TEMPLE'S RED STARBITS"),	_("SECRET OF WATER TEMPLE"))

COURSE_ACTS(COURSE_THI, _("13 STARDUST ISLES"),	_("THE ANCIENT RUINS"),	_("TOP OF STARDUST MOUNTAIN"),	_("SECRET OF THE STAR TEMPLE"),	_("8 RED STARBITS ACROSS STARDUST ISLES"),	_("STARDUST SKY FLIGHT"),	_("THE STARDUST MYSTERY"))

COURSE_ACTS(COURSE_TTC, _("14 SKY HIGH CANYON"),	_("TOP OF THE MOUNTAIN"),	_("THE GIANT SPIKE"),	_("THE LAVA CAVE"),	_("SECRET OF THE SKY PILLARS"),	_("8 SKY-HIGH RED STARBITS"),	_("TAKE DOWN THE PIRANHA PLANTS"))

COURSE_ACTS(COURSE_RR, _("15 STARLIGHT RAINBOW SKIES"),	_("RAINBOW VILLAGE"),	_("RAINBOW CASTLE IN THE SKY"),	_("ACROSS THE RAINBOW SKIES"),	_("THE RAINBOW STAR TOWER"),	_("8 RAINBOW SKY STARBITS"),	_("STARLIGHT SKY RAINBOW RINGS"))

SECRET_STAR(15, _("   BOWSER'S LAVA FORTRESS"))
SECRET_STAR(16, _("   BOWSER'S DARK MATTER BASE"))
SECRET_STAR(17, _("   THE SPACE FORTRESS"))
SECRET_STAR(18, _("   STARSHINE BEACH"))
SECRET_STAR(19, _("   SECRET METAL CAP CAVE"))
SECRET_STAR(20, _("   SKY TOWERS"))
SECRET_STAR(21, _("   BOO'S MANSION"))
SECRET_STAR(22, _("   STARDUST FIELD"))
SECRET_STAR(23, _("   PATH TO THE SPACE FORTRESS"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   SECRET STARS"))
EXTRA_TEXT(0,_("A SECRET STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
