COURSE_ACTS(COURSE_BOB, _(" 1 ICY LAKESIDE GOLF"),	_("GAP"),	_("FLAG"),	_("LEAF"),	_("BRIDGE"),	_("SHOOT"),	_("SANDY"))

COURSE_ACTS(COURSE_WF, _(" 2 SANDY WATER FIELDS"),	_("BEHIND"),	_("COLUMN"),	_("BLACK"),	_("SHELL"),	_("SWIM"),	_("WALLJUMP"))

COURSE_ACTS(COURSE_JRB, _(" 3 BURNING NIGHT HEIGHTS"),	_("BRIDGE"),	_("1-UP"),	_("SPOOKY"),	_("RING"),	_("TREE"),	_("CAVERN"))

COURSE_ACTS(COURSE_CCM, _(" 4 MIDNIGHT MOUNTAIN KAROX"),	_("START"),	_("CAGE"),	_("AMP"),	_("CAVE"),	_("FALL"),	_("JUMP"))

COURSE_ACTS(COURSE_BBH, _(" 5 STAR TREE VALLEY"),	_("TOWN"),	_("FORT"),	_("TOAST"),	_("STAR"),	_("ROOF"),	_("TRICKY"))

COURSE_ACTS(COURSE_HMC, _(" 6 QUICKSAND HABOR"),	_("EDGE"),	_("TIME"),	_("FIRE"),	_("WINDOW"),	_("WALLJUMP (NOT WALLKICK)"),	_("1-UP?"))

COURSE_ACTS(COURSE_LLL, _(" 7 DEAD FRANKOOPSKO"),	_("SEA"),	_("CLOSED"),	_("ROOF"),	_("GRAY"),	_("BOXES"),	_("TREE"))

COURSE_ACTS(COURSE_SSL, _(" 8 ORIENTAL SUNFLOWER PARK"),	_("MIMA"),	_("WALL"),	_("MAZE"),	_("HOLE"),	_("BLOCKED"),	_("YOSHI"))

COURSE_ACTS(COURSE_DDD, _(" 9 BLUE REALM: CASTLE DUTE"),	_("TOP"),	_("ROOF"),	_("INSIDE"),	_("DOWN"),	_("FAKE"),	_("FORT"))

COURSE_ACTS(COURSE_SL, _("HEY YOU"),	_("DANGEROUS PATH IN THE SKY"),	_("RIDE TO THE HEIGHEST POINT"),	_("INVESTIGATE THE INSIDE"),	_("8 CANDY COINS IN LOW CORNERS"),	_("HALL OF THE FAKE SUN STONES"),	_("SECRET OF THE DEEP SKY"))

COURSE_ACTS(COURSE_WDW, _("WHY ARE YOU IN THIS"),	_("A PIT FULL OF PLANTS"),	_("HURDLES WITH LITTLE TIME PRESSURE"),	_("DANGEROUS SNAKE PATH"),	_("ROTATING VANISH CAP FUN"),	_("MECHANISM OVER THE POWDER"),	_("A SOFT FLIGHT DOWNWARDS!"))

COURSE_ACTS(COURSE_TTM, _("SCREEN? NOBODY USES"),	_("LOST GATE SWITCH"),	_("A LITTLE VANISHING RUN"),	_("NO TIME FOR A BRIDGE"),	_("SOME MAGIC COINS, OH WELL"),	_("FLY OVER THE RUINS"),	_("CANDY COINS OF THE UNDERGROUND"))

COURSE_ACTS(COURSE_THI, _("THIS... WHAT IS WRONG?"),	_("LOOK OUT FOR SHROOMS"),	_("SECRET OF THE FLOWERS"),	_("HOT PASSAGE OF THE CASTLE"),	_("DO YOU HAVE A CAP WITH WINGS?"),	_("CANDY COINS OF THE PAST"),	_("SECRET OF THE WAY TO EVEN BEFOR"))

COURSE_ACTS(COURSE_TTC, _("FEELING BAD OR SAD?"),	_("GET ON THE CLOCK"),	_("BACK TO THE BOX JUMPING"),	_("HOT FOOT RACE"),	_("BEHIND THE FIERY PALM PARK"),	_("LAVA JUMPING FUN"),	_("DUDE, WHERE'S MAH KAIZO?"))

COURSE_ACTS(COURSE_RR, _("NOT MY PROBLEM LOL"),	_("CLIMB THE SMALL TOWER"),	_("BACKDOOR PATH"),	_("COINS OF THE BOXES"),	_("INVESTIGATE A FORT"),	_("CANDY COINS EVERYWHERE"),	_("TOWER OF PAIN"))

SECRET_STAR(15, _("   STONGEST ICE CASTLE"))
SECRET_STAR(16, _("   MISSING'S WATER WAREHOUSE"))
SECRET_STAR(17, _("   BRODUTE'S RACING FUN"))
SECRET_STAR(18, _("   MUSHROOM KINGDOM"))
SECRET_STAR(19, _("   M"))
SECRET_STAR(20, _("   W"))
SECRET_STAR(21, _("   KAPTHWOMP'S ARENA"))
SECRET_STAR(22, _("   YOSHI'S ISLAND 1"))
SECRET_STAR(23, _("   CASTLE UNDERGROUND"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   FLOWER'S SECRET STARS"))
EXTRA_TEXT(0,_("BRODUTE'S RACE IN THE BLUE REALM!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
