COURSE_ACTS(COURSE_BOB, _(" 1 PALM HARBOUR"),	_("1 CLIMB THE BOXES"),	_("2 BEHIND THE PALM PARK"),	_("3 TROPICAL KOOPA RACE"),	_("4 THE SEWER SYSTEM"),	_("5 HABOUR'S BLUE COINS"),	_("6 THE TOWER'S TOP"))

COURSE_ACTS(COURSE_WF, _(" 2 CARRAIG BEACH"),	_("1 SHOOT DOWN KLEPTO"),	_("2 ALONG THE CLIFF"),	_("3 UNDER CONSTRUCTION"),	_("4 SANDY 8 BLUE COINS"),	_("5 OPEN THE CLOSED GATE"),	_("6 SOME SPECIAL PLACES"))

COURSE_ACTS(COURSE_JRB, _(" 3 PARK AN GLEANN"),	_("1 MOUNTAIN'S GIGANT PLANTS"),	_("2 THE TOP OF MT. STACA"),	_("3 THE PIRANHA PLANT PATH"),	_("4 TICK TACK CAVE"),	_("5 CHILLING BLUE COINS"),	_("6 THE SECRET OF TREES"))

COURSE_ACTS(COURSE_CCM, _(" 4 CASTLE SAOIRE"),	_("1 THE BALCONY"),	_("2 SECRET OF THE GARDEN"),	_("3 LOOK AT ME"),	_("4 SPECIAL 5 BOXES"),	_("5 ROYAL BLUE COINS"),	_("6 BY THE SEWAGE"))

COURSE_ACTS(COURSE_BBH, _(" 5 ICY GREY CAVERNS"),	_("1 BEHIND THE LAVA"),	_("2 INTO THE COLOR GLITTER"),	_("3 DANGEROUS ICE WAY"),	_("4 THE TOWER OF FAKES"),	_("5 IN A SMALL TUNNEL"),	_("6 BLUE COINS IN GREY DEEPS"))

COURSE_ACTS(COURSE_HMC, _(" 6 ABHEINN FACTORY"),	_("1 BLOCKY PARKOUR"),	_("2 INSPECT THE FACTORY"),	_("3 OVER THE TOXIC POOL"),	_("4 TOP OF THE CONSTRUCTION"),	_("5 THE WARP-ZONE FINDER"),	_("6 BLUE RIVER GOLD"))

COURSE_ACTS(COURSE_LLL, _(" 7 SANDY TEAMPAILL"),	_("1 THE AMP KEEP"),	_("2 TOP OF A GIGANT CACTUS"),	_("3 THE GOLDEN PILLARS"),	_("4 CLIMB THE ACIENT BUILDING"),	_("5 BREAK IN THE TEMPEL"),	_("6 THE LOST COINS OF THE SAND"))

COURSE_ACTS(COURSE_SSL, _(" 8 VOLCANO LU'ITHREACH"),	_("1 FACE KING WHOMP'S BOX"),	_("2 BEHIND THE GLASS"),	_("3 OVER THE LAVA SEA"),	_("4 COLD COINS IN HOT TERETORY"),	_("5 CLIMP FOR THE WINGS"),	_("6 METAL COIN JUMPS"))

COURSE_ACTS(COURSE_DDD, _(" 9 Z"),	_("BOARD BOWSER'S SUB"),	_("666 STILL A TROLL"),	_("POLE-JUMPING FOR RED COINS"),	_("THROUGH THE JET STREAM"),	_("THE MANTA RAY'S REWARD"),	_("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 Z"),	_("SNOWMAN'S BIG HEAD"),	_("CHILL WITH THE BULLY"),	_("IN THE DEEP FREEZE"),	_("WHIRL FROM THE FREEZING POND"),	_("SHELL SHREDDIN' FOR RED COINS"),	_("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 Z"),	_("SHOCKING ARROW LIFTS!"),	_("TOP O' THE TOWN"),	_("SECRETS IN THE SHALLOWS & SKY"),	_("EXPRESS ELEVATOR--HURRY UP!"),	_("GO TO TOWN FOR RED COINS"),	_("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 Z"),	_("SCALE THE MOUNTAIN"),	_("MYSTERY OF THE MONKEY CAGE"),	_("SCARY 'SHROOMS, RED COINS"),	_("MYSTERIOUS MOUNTAINSIDE"),	_("BREATHTAKING VIEW FROM BRIDGE"),	_("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 Z"),	_("PLUCK THE PIRANHA FLOWER"),	_("THE TIP TOP OF THE HUGE ISLAND"),	_("REMATCH WITH KOOPA THE QUICK"),	_("FIVE ITTY BITTY SECRETS"),	_("WIGGLER'S RED COINS"),	_("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 Z"),	_("ROLL INTO THE CAGE"),	_("THE PIT AND THE PENDULUMS"),	_("GET A HAND"),	_("STOMP ON THE THWOMP"),	_("TIMED JUMPS ON MOVING BARS"),	_("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 Z"),	_("CRUISER CROSSING THE RAINBOW"),	_("THE BIG HOUSE IN THE SKY"),	_("COINS AMASSED IN A MAZE"),	_("SWINGIN' IN THE BREEZE"),	_("TRICKY TRIANGLES!"),	_("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(15, _("   BATTEL IN THE CAVES"))
SECRET_STAR(16, _("   THE ENDING ISLE"))
SECRET_STAR(17, _("   DORCHA WIGGLERS DESTINATION"))
SECRET_STAR(18, _("   MAJESTIC MOUNTAINS"))
SECRET_STAR(19, _("   Z"))
SECRET_STAR(20, _("   Z"))
SECRET_STAR(21, _("   Z"))
SECRET_STAR(22, _("   A BAD ENDING"))
SECRET_STAR(23, _("   LITTLE JAPAN"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   HIDDEN RAINBOW STARS"))
EXTRA_TEXT(0,_("A HIDDEN RAINBOW STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
